function setBrowserOptionsCallback(~, ~)
%function setBrowserOptionsCallback(~, ~)
%Set Browser Options.
%See DicomDBBrowser.doc (or pdf) for more information about options.
%
%Note: option settings must fit on one line and can contain one semicolon at most.
%Options can be strings, cell arrays of strings, or numerical arrays.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The DICOM Database Browser (dicomDBBrowser).
% 
% DicomDBBrowser development has been led by: Daniel Lafontaine
% 
% DicomDBBrowser is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of dicomDBBrowser is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% DicomDBBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with DicomDBBrowser.  If not, see <http://www.gnu.org/licenses/>.

    dlgOptions = ...
        dialog('Position', [(getBrowserMainWindowPosition('xpos')+(getBrowserMainWindowSize('xsize')/2)-370/2) ...
                            (getBrowserMainWindowPosition('ypos')+(getBrowserMainWindowSize('ysize')/2)-195/2) ...
                            370 ...
                            170 ...
                            ],...
               'Color', browserBackgroundColor('get'), ...
               'Name'    , 'Options'...
              );                         

%        javaFrame = get(dlgOptions,'JavaFrame');
%        javaFrame.setFigureIcon(javax.swing.ImageIcon('./logo.png'));             

        uicontrol(dlgOptions,...
                  'style'   , 'text',...
                  'string'  , 'DoubleClick Action',...
                  'horizontalalignment', 'left',...
                  'BackgroundColor', browserBackgroundColor('get'), ...
                  'ForegroundColor', browserForegroundColor('get'), ...                   
                  'position', [20 107 100 20]...
                  ); 

    dlgDoubleClick = ...
        uicontrol(dlgOptions,...
                  'Style'   , 'popup', ...
                  'Position', [130 110 200 25],...
                  'enable'  , 'on',...
                  'String'  ,  browserDoubleClickList(),...
                  'Value'   ,  browserDoubleClickOffset('get'), ...
                  'FontSize', 10, ...
                  'BackgroundColor', browserBackgroundColor('get'), ...
                  'ForegroundColor', browserForegroundColor('get') ...                     
                  );  

    chkbrowserFastSearch = ...
        uicontrol(dlgOptions,...
                  'style'   , 'checkbox',...
                  'enable'  , 'on',...
                  'value'   , browserFastSearch('get'),...
                  'position', [20 85 20 20],...
                  'BackgroundColor', browserBackgroundColor('get'), ...
                  'ForegroundColor', browserForegroundColor('get'), ...                     
                  'Callback', @browserFastSearchCallback...                          
                  );                      

        uicontrol(dlgOptions,...
                  'style'   , 'text',...
                  'string'  , 'Fast Search (one series per folder)',...
                  'horizontalalignment', 'left',...
                  'position', [40 82 200 20],...
                  'Enable', 'Inactive',...
                  'BackgroundColor', browserBackgroundColor('get'), ...
                  'ForegroundColor', browserForegroundColor('get'), ...                     
                  'ButtonDownFcn', @browserFastSearchCallback...                          
                  ); 

    chkbrowserMultiThread = ...
        uicontrol(dlgOptions,...
                  'style'   , 'checkbox',...
                  'enable'  , 'on',...
                  'value'   , browserMultiThread('get'),...
                  'position', [20 60 20 20],...
                  'BackgroundColor', browserBackgroundColor('get'), ...
                  'ForegroundColor', browserForegroundColor('get'), ...                     
                  'Callback', @browserMultiThreadCallback...                          
                  );                      

        uicontrol(dlgOptions,...
                  'style'   , 'text',...
                  'string'  , 'Browser Multi-Threading',...
                  'horizontalalignment', 'left',...
                  'position', [40 57 200 20],...
                  'Enable', 'Inactive',...
                  'BackgroundColor', browserBackgroundColor('get'), ...
                  'ForegroundColor', browserForegroundColor('get'), ...                     
                  'ButtonDownFcn', @browserMultiThreadCallback...                          
                  ); 


        uicontrol(dlgOptions,...
                  'String','Cancel',...
                  'Position',[290 7 75 25],...
                  'BackgroundColor', browserBackgroundColor('get'), ...
                  'ForegroundColor', browserForegroundColor('get'), ...                     
                   'Callback', @cancelBrowserOptionsCallback...
                  );  

        uicontrol(dlgOptions,...
                  'String','Ok',...
                  'Position',[210 7 75 25],...
                  'BackgroundColor', browserBackgroundColor('get'), ...
                  'ForegroundColor', browserForegroundColor('get'), ...                    
                  'Callback', @okBrowserOptionsCallback...
                  );   

    function browserFastSearchCallback(hObject, ~)    

        if get(chkbrowserFastSearch, 'Value')
            if strcmpi(get(hObject, 'Style'), 'checkbox')
                set(chkbrowserFastSearch, 'Value', true);
            else
                set(chkbrowserFastSearch, 'Value', false);
            end
        else
            if strcmp(hObject.Style, 'checkbox')
                set(chkbrowserFastSearch, 'Value', false);
            else
                set(chkbrowserFastSearch, 'Value', true);
            end
        end            
    end

    function browserMultiThreadCallback(hObject, ~)    

        if get(chkbrowserMultiThread, 'Value')
            if strcmpi(get(hObject, 'Style'), 'checkbox')
                set(chkbrowserMultiThread, 'Value', true);
            else
                set(chkbrowserMultiThread, 'Value', false);
            end
        else
            if strcmp(hObject.Style, 'checkbox')
                set(chkbrowserMultiThread, 'Value', false);
            else
                set(chkbrowserMultiThread, 'Value', true);
            end
        end            
    end


    function cancelBrowserOptionsCallback(~, ~)

        delete(dlgOptions);
    end

    function okBrowserOptionsCallback(~, ~)

        browserFastSearch('set', get(chkbrowserFastSearch, 'Value'));

        browserMultiThread('set', get(chkbrowserMultiThread, 'Value'));

        browserDoubleClickOffset('set', get(dlgDoubleClick, 'Value'));

        delete(dlgOptions);
    end           
end
