function browserInitAnonymizerValues() 
%function browserInitAnonymizerValues() 
%Anonymizer Main Function.
%See dicomDBBrowser.doc (or pdf) for more information about options.
%
%Note: option settings must fit on one line and can contain one semicolon at most.
%Options can be strings, cell arrays of strings, or numerical arrays.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The DICOM Database Browser (dicomDBBrowser).
% 
% TriDFusion development has been led by: Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of dicomDBBrowser is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% dicomDBBrowser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with dicomDBBrowser.  If not, see <http://www.gnu.org/licenses/>.

    dlgSetAnon = ...
        dialog('Position', [(getBrowserMainWindowPosition('xpos')+(getBrowserMainWindowSize('xsize')/2)-480/2) ...
                            (getBrowserMainWindowPosition('ypos')+(getBrowserMainWindowSize('ysize')/2)-500/2) ...
                            480 ...
                            500],...
               'Name'    , 'Data Anonymization'...
              );

%                javaFrame = get(dlgSetAnon,'JavaFrame');
%                javaFrame.setFigureIcon(javax.swing.ImageIcon('./logo.png'));    

    % PatientName %                                

        uicontrol(dlgSetAnon,...
                  'style'   , 'text',...
                  'string'  , 'Patient Name',...
                  'horizontalalignment', 'left',...
                  'position', [20 452 100 20]...
                  );

    edtPatientName = ...
        uicontrol(dlgSetAnon,...
                  'enable'    , 'on',...
                  'style'     , 'edit',...
                  'Background', 'white',...
                  'string'    , ['ANO_' num2str(randi(999999999999))],...
                  'position'  , [160 455 300 20]...
                 );                                
    % PatientID %                                                                

        uicontrol(dlgSetAnon,...
                  'style'   , 'text',...
                  'string'  , 'Patient ID',...
                  'horizontalalignment', 'left',...
                  'position', [20 427 100 20]...
                  );  

     edtPatientID = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , ['ANO_' num2str(randi(999999999999))],...
                   'position'  , [160 430 300 20]...
                    );  

    % PatientBirthDate %

     uicontrol(dlgSetAnon,...
              'style'   , 'text',...
              'string'  , 'Patient Birth Date',...
              'horizontalalignment', 'left',...
              'position', [20 402 100 20]...                 
              );

     edtPatientBirthDate = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '16000101',...
                   'position'  , [160 405 100 20]...
                   );

     % PatientSex %                                    

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Patient Gender',...
                   'horizontalalignment', 'left',...
                   'position', [20 377 100 20]...                        
                   );

     edtPatientSex = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '',...
                   'position'  , [160 380 100 20]...
                   );

      % AccessionNumber %                                   

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Accession Number',...
                   'horizontalalignment', 'left',...
                   'position', [20 352 100 20]...                 
                   );

     edtAccessionNumber = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , ['ANO_' num2str(randi(999999999999))],...
                   'position'  , [160 355 300 20]...
                   ); 

      % StudyDescription %                              

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Study Description',...
                   'horizontalalignment', 'left',...
                   'position', [20 327 100 20]...                  
                   );

     edtStudyDescription = uicontrol(dlgSetAnon,...
                       'enable'    , 'on',...
                       'style'     , 'edit',...
                       'Background', 'white',...
                       'string'    , ['ANO_' num2str(randi(999999999999))],...
                       'position'  , [160 330 300 20]...
                       ); 

      % SeriesDescription %                       

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Series Description',...
                   'horizontalalignment', 'left',...
                   'position', [20 302 100 20]...                     
                   );

     edtSeriesDescription = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , ['ANO_' num2str(randi(999999999999))],...
                   'position'  , [160 305 300 20]...
                   ); 

     % StudyInstanceUID %

     chkStudyInstanceUID = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 280 20 20]...
                   );                      

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'New Study UID',...
                   'horizontalalignment', 'left',...
                   'position', [40 277 100 20],...
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtStudyInstanceUIDCallback ...
                   );

     % SeriesInstanceUID %

     chkSeriesInstanceUID = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 255 20 20]...
                   );                      

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'New Series UID',...
                   'horizontalalignment', 'left',...
                   'position', [40 252 100 20],...
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtSeriesInstanceUIDCallback ...                         
                   );

    % StudyDate %

     chkStudyDate = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 230 20 20],...
                   'Callback', @chkStudyDateCallback ... 
                   );  

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Study Date',...
                   'horizontalalignment', 'left',...
                   'position', [40 227 100 20],...                 
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtStudyDateCallback ... 
                   );

     edtStudyDate = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '16000101',...
                   'position'  , [160 230 100 20]...
                   );

     % SeriesDate %

     chkSeriesDate = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 205 20 20],...
                   'Callback', @chkSeriesDateCallback ... 
                   ); 

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Series Date',...
                   'horizontalalignment', 'left',...
                   'position', [40 202 100 20],...                 
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtSeriesDateCallback ... 
                   );

     edtSeriesDate = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '16000101',...
                   'position'  , [160 205 100 20]...
                   );

     % AcquisitionDate %

     chkAcquisitionDate = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 180 20 20],...
                   'Callback', @chkAcquisitionDateCallback ... 
                   ); 

        uicontrol(dlgSetAnon,...
                  'style'   , 'text',...
                  'string'  , 'Acquisition Date',...
                  'horizontalalignment', 'left',...
                  'position', [40 177 100 20],...                 
                  'Enable'  , 'Inactive',... 
                  'ButtonDownFcn', @txtAcquisitionDateCallback ... 
                  );

     edtAcquisitionDate = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '16000101',...
                   'position'  , [160 180 100 20]...
                   );

     % ContentDate %

     chkContentDate = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 155 20 20],...
                   'Callback', @chkContentDateCallback ... 
                   ); 

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Content Date',...
                   'horizontalalignment', 'left',...
                   'position', [40 152 100 20],...                 
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtContentDateCallback ... 
                   );

     edtContentDate = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '16000101',...
                   'position'  , [160 155 100 20]...
                   );

     % StudyTime %

     chkStudyTime = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 130 20 20],...
                   'Callback', @chkStudyTimeCallback ... 
                   ); 

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Study Time',...
                   'horizontalalignment', 'left',...
                   'position', [40 127 100 20],...                 
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtStudyTimeCallback ... 
                   );

     edtStudyTime = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '000000',...
                   'position'  , [160 130 100 20]...
                   );        

     % SeriesTime %

     chkSeriesTime = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 105 20 20],...
                   'Callback', @chkSeriesTimeCallback ... 
                   ); 

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Series Time',...
                   'horizontalalignment', 'left',...
                   'position', [40 102 100 20],...                 
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtSeriesTimeCallback ... 
                   );

     edtSeriesTime = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '000000',...
                   'position'  , [160 105 100 20]...
                   );     

     % AcquisitionTime %

     chkAcquisitionTime = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 80 20 20],...
                   'Callback', @chkAcquisitionTimeCallback ... 
                   ); 

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Acquisition Time',...
                   'horizontalalignment', 'left',...
                   'position', [40 77 100 20],...                 
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtAcquisitionTimeCallback ... 
                   );

     edtAcquisitionTime = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '000000',...
                   'position'  , [160 80 100 20]...
                   );  

     % ContentTime %

     chkContentTime = ...
         uicontrol(dlgSetAnon,...
                   'style'   , 'checkbox',...
                   'enable'  , 'on',...
                   'value'   , 1,...
                   'position', [20 55 20 20],...
                   'Callback', @chkContentTimeCallback ... 
                   ); 

         uicontrol(dlgSetAnon,...
                   'style'   , 'text',...
                   'string'  , 'Content Time',...
                   'horizontalalignment', 'left',...
                   'position', [40 52 100 20],...                 
                   'Enable'  , 'Inactive',... 
                   'ButtonDownFcn', @txtContentTimeCallback ... 
                   );

     edtContentTime = ...
         uicontrol(dlgSetAnon,...
                   'enable'    , 'on',...
                   'style'     , 'edit',...
                   'Background', 'white',...
                   'string'    , '000000',...
                   'position'  , [160 55 100 20]...
                   ); 

        uicontrol(dlgSetAnon,...
                  'String'  ,'Cancel',...
                  'Position',[370 8 100 25],...
                  'Callback', @cancelAnonymizerValuesCallback...
                  );  

    uiSetAnonymizerValues = ...
        uicontrol(dlgSetAnon,...
                  'String','Proceed',...
                  'Position',[265 8 100 25],...
                  'Callback', @setAnonymizerValuesCallback...
                  );       

    waitfor(uiSetAnonymizerValues);

    function chkStudyDateCallback(hObject,~)
        if hObject.Value == 1
            edtStudyDate.Enable = 'on';
        else
            edtStudyDate.Enable = 'off';                        
        end
    end

    function txtStudyDateCallback(~,~)
        if chkStudyDate.Value == 1
            chkStudyDate.Value = 0;
            edtStudyDate.Enable = 'off';
        else    
            chkStudyDate.Value = 1;
            edtStudyDate.Enable = 'on';
        end
    end               

    function chkSeriesDateCallback(hObject,~)
        if hObject.Value == 1
            edtSeriesDate.Enable = 'on';
        else
            edtSeriesDate.Enable = 'off';                        
        end
    end

    function txtSeriesDateCallback(~,~)
        if chkSeriesDate.Value == 1
            chkSeriesDate.Value = 0;
            edtSeriesDate.Enable = 'off';
        else    
            chkSeriesDate.Value = 1;
            edtSeriesDate.Enable = 'on';
        end
    end

    function chkAcquisitionDateCallback(hObject,~)
        if hObject.Value == 1
            edtAcquisitionDate.Enable = 'on';
        else
            edtAcquisitionDate.Enable = 'off';                        
        end
    end

    function txtAcquisitionDateCallback(~,~)
        if chkAcquisitionDate.Value == 1
            chkAcquisitionDate.Value = 0;
            edtAcquisitionDate.Enable = 'off';
        else    
            chkAcquisitionDate.Value = 1;
            edtAcquisitionDate.Enable = 'on';
        end
    end

    function chkContentDateCallback(hObject,~)
        if hObject.Value == 1
            edtContentDate.Enable = 'on';
        else
            edtContentDate.Enable = 'off';                        
        end
    end

    function txtContentDateCallback(~,~)
        if chkContentDate.Value == 1
            chkContentDate.Value = 0;
            edtContentDate.Enable = 'off';
        else    
            chkContentDate.Value = 1;
            edtContentDate.Enable = 'on';
        end
    end

    function chkStudyTimeCallback(hObject,~)
        if hObject.Value == 1
            edtStudyTime.Enable = 'on';
        else
            edtStudyTime.Enable = 'off';                        
        end
    end

    function txtStudyTimeCallback(~,~)
        if chkStudyTime.Value == 1
            chkStudyTime.Value = 0;
            edtStudyTime.Enable = 'off';
        else    
            chkStudyTime.Value = 1;
            edtStudyTime.Enable = 'on';
        end
    end

    function chkSeriesTimeCallback(hObject,~)
        if hObject.Value == 1
            edtSeriesTime.Enable = 'on';
        else
            edtSeriesTime.Enable = 'off';                        
        end
    end

    function txtSeriesTimeCallback(~,~)
        if chkSeriesTime.Value == 1
            chkSeriesTime.Value = 0;
            edtSeriesTime.Enable = 'off';
        else    
            chkSeriesTime.Value = 1;
            edtSeriesTime.Enable = 'on';
        end
    end

    function chkAcquisitionTimeCallback(hObject,~)
        if hObject.Value == 1
            edtAcquisitionTime.Enable = 'on';
        else
            edtAcquisitionTime.Enable = 'off';                        
        end
    end

    function txtAcquisitionTimeCallback(~,~)
        if chkAcquisitionTime.Value == 1
            chkAcquisitionTime.Value = 0;
            edtAcquisitionTime.Enable = 'off';
        else    
            chkAcquisitionTime.Value = 1;
            edtAcquisitionTime.Enable = 'on';
        end
    end 

    function chkContentTimeCallback(hObject,~)
        if hObject.Value == 1
            edtContentTime.Enable = 'on';
        else
            edtContentTime.Enable = 'off';                        
        end
    end

    function txtContentTimeCallback(~,~)
        if chkContentTime.Value == 1
            chkContentTime.Value = 0;
            edtContentTime.Enable = 'off';
        else    
            chkContentTime.Value = 1;
            edtContentTime.Enable = 'on';
        end
    end    

    function txtStudyInstanceUIDCallback(~,~)
        if chkStudyInstanceUID.Value == 1
            chkStudyInstanceUID.Value = 0;
        else    
            chkStudyInstanceUID.Value = 1;
        end                    
    end

    function txtSeriesInstanceUIDCallback(~,~)
        if chkSeriesInstanceUID.Value == 1
            chkSeriesInstanceUID.Value = 0;
        else    
            chkSeriesInstanceUID.Value = 1;
        end
    end     

    function setAnonymizerValuesCallback(~,~)    

        tValues = '';

        tValues.PatientName       = edtPatientName.String;
        tValues.PatientID         = edtPatientID.String;
        tValues.PatientBirthDate  = edtPatientBirthDate.String;
        tValues.PatientSex        = edtPatientSex.String;
        tValues.AccessionNumber   = edtAccessionNumber.String;
        tValues.StudyDescription  = edtStudyDescription.String;
        tValues.SeriesDescription = edtSeriesDescription.String;
        tValues.SourceApplicationEntityTitle = 'TRIDFUSION';

        if chkStudyDate.Value == 1                     
            tValues.StudyDate = ...
                edtStudyDate.String;
        end

        if chkSeriesDate.Value == 1                     
            tValues.SeriesDate = ...
                edtSeriesDate.String;
        end

        if chkAcquisitionDate.Value == 1                     
            tValues.AcquisitionDate = ...
                edtAcquisitionDate.String;
        end

        if chkContentDate.Value == 1                     
            tValues.ContentDate = ...
                edtContentDate.String;                                                            
        end
        if chkStudyTime.Value == 1                     
            tValues.StudyTime = ...
                edtStudyTime.String;
        end

        if chkSeriesTime.Value == 1                     
            tValues.SeriesTime = ...
            edtSeriesTime.String;
        end

        if chkAcquisitionTime.Value == 1                     
            tValues.AcquisitionTime = ...
                edtAcquisitionTime.String;   
        end

        if chkContentTime.Value == 1 
            tValues.ContentTime = ...
                edtContentTime.String;                                                                               
        end    

        if chkStudyInstanceUID.Value == 1
            tValues.StudyInstanceUID = dicomuid;
        end

        if chkSeriesInstanceUID.Value == 1
            tValues.SeriesInstanceUID = dicomuid;
        end

        browserAnonymizerValues('set', tValues);

        delete(dlgSetAnon);

    end

    function cancelAnonymizerValuesCallback(~,~)

        browserAnonymizerValues('set', '');

        delete(dlgSetAnon);  
    end
end
